def get_ffmpeg_template():
    """
    Returns a template string for FFMPEG command to merge images and audio.
    This is a placeholder for the complex filter graph required for the project.
    """
    # Placeholder template based on the requirement:
    # "Comando ffmpeg com o filtro amix e duration=first"
    template = (
        "ffmpeg -y "
        "-loop 1 -i {image_path} "
        "-i {audio_path} "
        "-filter_complex "
        "\"[1:a]volume=1.0[a1];[a1]amix=inputs=1:duration=first[aout]\" "
        "-map 0:v -map \"[aout]\" "
        "-c:v libx264 -tune stillimage -c:a aac -b:a 192k -pix_fmt yuv420p "
        "-shortest "
        "{output_path}"
    )
    return template

def get_karaoke_ass_header(title):
    """
    Returns the header for an .ass subtitle file with Karaoke effect.
    """
    header = f"""[Script Info]
; Script generated by Python Video Automation
Title: {title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1080
PlayResY: 1920

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Karaoke,Arial,60,&H00FFFFFF,&H0000FFFF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    return header
